DEFAULT_SERVER_CONFIG = """[options]
admin_passwd = odoo!-_v19_@dm!N
db_host = 127.0.0.1
db_port = 6432
db_user = serpentcs
db_password = serpentcs
addons_path = /home/serpentcs/workspace/odoo_ee/19.0EE,/home/serpentcs/workspace/odoo_ce/19.0CE/addons,/home/serpentcs/workspace/odoo_ce/19.0CE/odoo/addons
list_db=False
limit_request = 8192
cpu_time_limit = 300
limit_time_real = 300
http_port = 
dbfilter = ^$ """